export const iconsTraduzidos = [
  // Alimentação
  { nome: "Comida", icon: "restaurant", lib: "MaterialIcons" },
  { nome: "Mercado", icon: "shopping-cart", lib: "Feather" },
  { nome: "Transporte", icon: "car", lib: "FontAwesome5" },
  { nome: "Combustível", icon: "gas-pump", lib: "FontAwesome5" },
  { nome: "Estacionamento", icon: "parking", lib: "MaterialCommunityIcons" },
  { nome: "Trabalho", icon: "briefcase", lib: "Feather" },
  { nome: "Salário", icon: "dollar-sign", lib: "Feather" },
  { nome: "Investimentos", icon: "trending-up", lib: "Feather" },
  { nome: "Lazer", icon: "beer", lib: "FontAwesome5" },
  { nome: "Cinema", icon: "film", lib: "Feather" },
  { nome: "Shows", icon: "music", lib: "Feather" },
  { nome: "Streaming", icon: "play-circle", lib: "Feather" },
  { nome: "Jogos", icon: "gamepad", lib: "FontAwesome5" },
  { nome: "Educação", icon: "book", lib: "Feather" },
  { nome: "Cursos", icon: "school", lib: "MaterialIcons" },
  { nome: "Livros", icon: "book-open", lib: "Feather" },

  // Casa e contas
  { nome: "Casa", icon: "home", lib: "Feather" },
  { nome: "Aluguel", icon: "key", lib: "Feather" },
  { nome: "Reforma", icon: "hammer-screwdriver", lib: "MaterialCommunityIcons" },
  { nome: "Energia", icon: "bolt", lib: "FontAwesome5" },
  { nome: "Água", icon: "tint", lib: "FontAwesome5" },
  { nome: "Internet", icon: "wifi", lib: "Feather" },
  { nome: "Telefone", icon: "phone", lib: "Feather" },
  { nome: "Impostos", icon: "file-invoice-dollar", lib: "FontAwesome5" },

  // Saúde
  { nome: "Saúde", icon: "heart", lib: "Feather" },
  { nome: "Remédios", icon: "pill", lib: "MaterialCommunityIcons" },
  { nome: "Hospital", icon: "hospital", lib: "FontAwesome5" },
  { nome: "Exames", icon: "stethoscope", lib: "FontAwesome5" },

  // Animais
  { nome: "Animais", icon: "paw", lib: "FontAwesome5" },
  { nome: "Veterinário", icon: "bandage", lib: "Ionicons" },
  { nome: "Pet Shop", icon: "bone", lib: "MaterialCommunityIcons" },

  // Estilo pessoal
  { nome: "Roupas", icon: "shopping-bag", lib: "Feather" },
  { nome: "Calçados", icon: "shoe-print", lib: "MaterialCommunityIcons" },
  { nome: "Acessórios", icon: "watch", lib: "Feather" },
  { nome: "Beleza", icon: "spa", lib: "MaterialIcons" },
  { nome: "Cabelereiro", icon: "content-cut", lib: "MaterialIcons" },
  { nome: "Manicure", icon: "hand-heart", lib: "MaterialCommunityIcons" },
  { nome: "Maquiagem", icon: "lipstick", lib: "MaterialCommunityIcons" },

  // Viagem e lazer
  { nome: "Viagem", icon: "airplane", lib: "Ionicons" },
  { nome: "Hotel", icon: "bed", lib: "FontAwesome5" },
  { nome: "Transporte público", icon: "bus", lib: "FontAwesome5" },
  { nome: "Táxi", icon: "taxi", lib: "FontAwesome5" },
  { nome: "Uber", icon: "car-sport", lib: "Ionicons" },

  // Financeiro
  { nome: "Doações", icon: "hand-holding-heart", lib: "FontAwesome5" },
  { nome: "Presentes", icon: "gift", lib: "Feather" },
  { nome: "Família", icon: "users", lib: "Feather" },
  { nome: "Filhos", icon: "baby", lib: "FontAwesome5" },
  { nome: "Casamento", icon: "ring", lib: "MaterialCommunityIcons" },
  { nome: "Festas", icon: "party-popper", lib: "MaterialCommunityIcons" },
  { nome: "Bebidas", icon: "wine-glass", lib: "FontAwesome5" },
  { nome: "Café", icon: "coffee", lib: "Feather" },
  { nome: "Padaria", icon: "bread-slice", lib: "MaterialCommunityIcons" },
  { nome: "Restaurante", icon: "utensils", lib: "FontAwesome5" },
  { nome: "Fast Food", icon: "hamburger", lib: "FontAwesome5" },
  { nome: "Eletrônicos", icon: "tv", lib: "Feather" },
  { nome: "Computador", icon: "monitor", lib: "Feather" },
  { nome: "Celular", icon: "smartphone", lib: "Feather" },
  { nome: "Cartão de crédito", icon: "credit-card", lib: "Feather" },
  { nome: "Banco", icon: "university", lib: "FontAwesome5" },
  { nome: "Empréstimos", icon: "hand-holding-usd", lib: "FontAwesome5" },
  { nome: "Economia", icon: "piggy-bank", lib: "FontAwesome5" },
  { nome: "Poupança", icon: "safe", lib: "MaterialCommunityIcons" },

  // Serviços
  { nome: "Conserto", icon: "tools", lib: "MaterialCommunityIcons" },
  { nome: "Limpeza", icon: "broom", lib: "FontAwesome5" },
  { nome: "Seguros", icon: "shield", lib: "Feather" },
  { nome: "Documentos", icon: "file-text", lib: "Feather" },
  { nome: "Correios", icon: "mailbox", lib: "MaterialCommunityIcons" },

  // Esportes e hobbies
  { nome: "Esportes", icon: "dumbbell", lib: "FontAwesome5" },
  { nome: "Academia", icon: "activity", lib: "Feather" },
  { nome: "Corrida", icon: "run", lib: "MaterialCommunityIcons" },
  { nome: "Bicicleta", icon: "bicycle", lib: "FontAwesome5" },
  { nome: "Futebol", icon: "football", lib: "Ionicons" },
  { nome: "Basquete", icon: "basketball", lib: "Ionicons" },
  { nome: "Música", icon: "music", lib: "Feather" },
  { nome: "Instrumentos", icon: "guitar", lib: "Feather" },
  { nome: "Fotografia", icon: "camera", lib: "Feather" },
  { nome: "Arte", icon: "palette", lib: "FontAwesome5" },

  // Diversos
  { nome: "Religião", icon: "church", lib: "FontAwesome5" },
  { nome: "Caridade", icon: "hand-holding-heart", lib: "FontAwesome5" },
  { nome: "Outros", icon: "dots-horizontal", lib: "MaterialCommunityIcons" },
  { nome: "Emergência", icon: "alert-triangle", lib: "Feather" },
  { nome: "Reserva", icon: "lock", lib: "Feather" },
  { nome: "Meta", icon: "target", lib: "Feather" },
  { nome: "Planejamento", icon: "calendar", lib: "Feather" },
  { nome: "Imprevistos", icon: "help-circle", lib: "Feather" },
  { nome: "Reembolsos", icon: "rotate-ccw", lib: "Feather" },
  { nome: "Lucros", icon: "dollar-sign", lib: "Feather" },
  { nome: "Despesas", icon: "minus-circle", lib: "Feather" },
  { nome: "Ganhos", icon: "plus-circle", lib: "Feather" },
  { nome: "Eventos", icon: "calendar-check", lib: "FontAwesome5" },
  { nome: "Trânsito", icon: "traffic-cone", lib: "MaterialCommunityIcons" },
  { nome: "Serviços públicos", icon: "city", lib: "MaterialCommunityIcons" },
];
